services:
  - type: web
    name: url-shortener
    runtime: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -Dspring.profiles.active=prod -jar target/urlshortener-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod